<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}

$wgSitename         = "Linux and Unix Users Group at Virginia Tech Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgArticlePath      = "/wiki/$1";
$wgUsePathInfo      = true;
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "wiki@vtluug.org";
$wgPasswordSender = "wiki@vtluug.org";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "postgres";
$wgDBserver         = "localhost";
$wgDBname           = "mediawiki";
$wgDBuser           = "vtluug_wiki";
$wgDBpassword       = "ah(o4Weipughahv";

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "vtluug_wiki";
$wgDBts2schema      = "public";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads	= true;
$wgUploadDirectory  = "{$IP}/images/vtluug.org";
# $wgUseImageMagick	= true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

$wgUseSharedUploads            = true;
$wgSharedUploadPath            = "https://vtluug.org/w/images";
$wgSharedUploadDirectory       = '/srv/http/uniluug.org/w/images/uniluug.org';
$wgHashedSharedUploadDirectory = true;
$wgRepositoryBaseUrl           = "https://vtluug.org/wiki/Image:";

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache/vtluug";

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "45af9447485a3d226daadb6276e2749b8f1f60af776d4f18aa94cdebbbd15695";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = "Linux_and_Unix_Users_Group_at_Virginia_Tech_Wiki:License";
$wgRightsUrl = "http://creativecommons.org/licenses/by-sa/3.0/us/";
$wgRightsText = "Attribution-Share Alike 3.0 United States";
$wgRightsIcon = "$wgScriptPath/images/cc-by-sa.png";
# $wgRightsCode = "[license_code]"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

# HokieTux posing for The Free Hokie Reference
$wgLogo = "$wgScriptPath/images/VTLUUG_Wiki.png";

# Use secure cookies
$wgCookieSecure = true;

# Namespaces {{{
$wgExtraNamespaces[500] = "VTLUUG";
$wgExtraNamespaces[501] = "VTLUUG Talk";
$wgContentNamespaces[]  = 500;

$wgExtraNamespaces[502] = "Infrastructure";
$wgExtraNamespaces[503] = "Infrastructure talk";
$wgContentNamespaces[]  = 502;

$wgNamespaceProtection[502] = array('infrastructure-edit');
# }}}

# Groups {{{
$wgGroupPermissions['members']  = $wgGroupPermissions['user'];
$wgGroupPermissions['alumni']   = $wgGroupPermissions['members'];

$wgGroupPermissions['officers'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['officers']['infrastructure-edit'] = true;
# }}}

# LDAP {{{
require_once('extensions/LdapAuthentication/LdapAuthentication.php');
$wgAuth = new LdapAuthenticationPlugin();
 
$wgLDAPDomainNames          = array("VTLUUG");
$wgLDAPServerNames          = array("VTLUUG" => "razor.vtluug.org");
$wgLDAPEncryptionType       = array("VTLUUG" => "ssl");
$wgLDAPSearchAttributes     = array("VTLUUG" => "uid");
$wgLDAPBaseDNs              = array("VTLUUG" => "dc=vtluug,dc=org");
$wgLDAPLowerCaseUsername    = array("VTLUUG" => true);
$wgLDAPUseLDAPGroups        = array("VTLUUG" => true);
$wgLDAPGroupUseFullDN       = array("VTLUUG" => false);
$wgLDAPGroupObjectclass     = array("VTLUUG" => "posixgroup");
$wgLDAPGroupAttribute       = array("VTLUUG" => "memberuid");
$wgLDAPGroupNameAttribute   = array("VTLUUG" => "cn");

$wgLDAPPreferences = array(
    "VTLUUG" => array(
        'email' => 'mail',
        'realname' => 'cn',
    ),
);

$wgMinimalPasswordLength = 1;
# }}}

# Favicons
$wgAppleTouchIcon = "/files/icons/icon.png";
$wgFavicon = "/files/icons/favicon.png";

# Citations and references
wfLoadExtension("Cite");

# Parser functions
wfLoadExtension("ParserFunctions");

# Template transcluding (for Uniluug)
$wgEnableScaryTranscluding = true;
$wgTranscludeCacheExpiry = 3600;

# API Settings
$wgEnableAPI = true;
$wgEnableWriteAPI = true;
